name: Continuous Integration

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: >
          docker build -t csharp-sdk-example --progress=plain .
          --build-arg KEY=${{ secrets.SDK_KEY }}
          --build-arg SECRET=${{ secrets.SDK_SECRET }}
          --build-arg CONDUCTOR_SERVER_URL=${{ secrets.CONDUCTOR_SERVER_URL }}
      - name: Run
        run: docker run csharp-sdk-example

