name: Continuous Integration

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linter
        run: >
          DOCKER_BUILDKIT=1 docker build .
            --progress=plain
            --target=lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: >
          DOCKER_BUILDKIT=1 docker build .            
            --build-arg KEY=${{ secrets.SDK_INTEGRATION_TESTS_SERVER_KEY_ID }}
            --build-arg SECRET=${{ secrets.SDK_INTEGRATION_TESTS_SERVER_KEY_SECRET }}
            --build-arg CONDUCTOR_SERVER_URL=${{ secrets.SDK_INTEGRATION_TESTS_SERVER_API_URL }}
            --target=test
