name: Continuous Integration

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linter
        run: >
          DOCKER_BUILDKIT=1 docker build
            --progress=plain
            --target=lint
            .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: >
          DOCKER_BUILDKIT=1 docker build
            --target=test
            --progress=plain
            --build-arg KEY=${{ secrets.SDK_KEY }}
            --build-arg SECRET=${{ secrets.SDK_SECRET }}
            --build-arg CONDUCTOR_SERVER_URL=${{ secrets.CONDUCTOR_SERVER_URL }}
            .
