name: Continuous Integration

on: pull_request

env:
  IMAGE_NAME: csharp-sdk-examples

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: docker build . -t $IMAGE_NAME
      - name: Set up ENVs
        run: >
          echo "KEY=${{ secrets.SDK_KEY }}" >> .env
          echo "SECRET=${{ secrets.SDK_SECRET }}" >> .env
          echo "CONDUCTOR_SERVER_URL=${{ secrets.CONDUCTOR_SERVER_URL }}" >> .env
      - name: Run
        run: docker run --env-file .env $IMAGE_NAME
